allowBuilds:
  "@parcel/watcher": true
  cypress: true
  esbuild: true

minimumReleaseAgeExclude:
  - "@11ty/eleventy@3.1.6"
  - "@11ty/eleventy-plugin-syntaxhighlight@5.0.2"
  - sass@1.101.7

nodeLinker: hoisted

updateConfig:
  ignoreDependencies:
    - "@types/node"
    - typescript
