#!/bin/sh
# Auto-generated by coily. Do not edit; regenerate via coily lockdown --apply --replace.
#
# Delegates to agent-guard hook pre-tool-use, which implements:
#   1. Binary-path check for known guard binaries (agent-guard, coily).
#   2. Routing-hint surface for wrapped binaries (gh, aws, kubectl, ...).
#
# Supersedes the prior 159-line deny script. See coilysiren/coily#185.
exec agent-guard hook pre-tool-use
