#!/bin/sh
# Auto-generated by coily. Do not edit; regenerate via coily setup or
# coily lockdown --apply --replace.
#
# PreToolUse Bash hook for Claude Code Desktop, where the built-in
# permissions.deny matcher is silently bypassed (verified 2026-04-23 on
# v2.1.119). On the CLI the built-in matcher is the primary gate; this
# hook is defense-in-depth there. On Desktop this hook is the only gate.
#
# Reads tool-input JSON on stdin, extracts tool_input.command, splits on
# common shell separators, strips leading "env VAR=val" tokens, then
# applies content-based and prefix-based deny checks. Exits 2 with a
# stderr message on hit.

set -u

INPUT=$(cat)
# Pull tool_input.command via a single-line sed. JSON parsing in pure sh
# is fragile; this matches Claude Code's well-formed input. Backslash-
# escapes in the original command are not unescaped here - the leading-
# token compare is robust to that as long as the binary name itself does
# not contain escapes (it never does in practice).
CMD=$(printf '%s' "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
if [ -z "$CMD" ]; then
  exit 0
fi

# Split CMD into segments at shell separators. A segment is the leading
# command of a pipeline / boolean / sequence / command substitution.
SEGMENTS=$(printf '%s\n' "$CMD" | awk '
{
  s = $0
  gsub(/\$\(/, "\n", s)
  gsub(/\)/,   "\n", s)
  gsub(/\|\|/, "\n", s)
  gsub(/&&/,   "\n", s)
  gsub(/[|;&]/, "\n", s)
  print s
}')

check_segment() {
  seg=$1
  # Strip leading whitespace.
  seg=$(printf '%s' "$seg" | sed -E 's/^[[:space:]]+//')
  [ -z "$seg" ] && return 0
  # Strip leading "env VAR=val ..." tokens (env on its own is denied
  # anyway, but env-prefixed invocations of an allowed binary should be
  # tested against the underlying binary).
  while printf '%s' "$seg" | grep -qE '^env( +[A-Za-z_][A-Za-z0-9_]*=[^ ]+)+( +|$)'; do
    seg=$(printf '%s' "$seg" | sed -E 's/^env( +[A-Za-z_][A-Za-z0-9_]*=[^ ]+)+( +|$)//')
  done
  # Coily binary check: reject any invocation that resolves to a coily
  # binary outside the homebrew install paths. Catches bare-name (PATH
  # lookup) and explicit-path forms (absolute or */coily). This is a
  # content-based check, not a leading-token literal match, so it lives
  # outside the case statement below.
  seg_first=${seg%% *}
  case "$seg_first" in
    coily)
      coily_path=$(command -v coily 2>/dev/null || true)
      case "$coily_path" in
        "") ;; # not on PATH; let bash report command-not-found
        "/opt/homebrew/bin/coily") ;;
        "/usr/local/bin/coily") ;;
        "/home/linuxbrew/.linuxbrew/bin/coily") ;;
        *) printf 'lockdown: blocked: coily resolves to %s, which is not a homebrew install (allowed: /opt/homebrew/bin/coily, /usr/local/bin/coily, /home/linuxbrew/.linuxbrew/bin/coily)\n' "$coily_path" >&2; exit 2 ;;
      esac
      ;;
    */coily)
      case "$seg_first" in
        "/opt/homebrew/bin/coily") ;;
        "/usr/local/bin/coily") ;;
        "/home/linuxbrew/.linuxbrew/bin/coily") ;;
        *) printf 'lockdown: blocked: coily binary at %s is not a homebrew install (allowed: /opt/homebrew/bin/coily, /usr/local/bin/coily, /home/linuxbrew/.linuxbrew/bin/coily)\n' "$seg_first" >&2; exit 2 ;;
      esac
      ;;
  esac
  case "$seg" in
    "aws cloudformation create-change-set"|"aws cloudformation create-change-set "*) printf 'lockdown: blocked by deny rule: aws cloudformation create-change-set\n' >&2; exit 2 ;;
    "aws cloudformation create-stack"|"aws cloudformation create-stack "*) printf 'lockdown: blocked by deny rule: aws cloudformation create-stack\n' >&2; exit 2 ;;
    "aws cloudformation delete-stack"|"aws cloudformation delete-stack "*) printf 'lockdown: blocked by deny rule: aws cloudformation delete-stack\n' >&2; exit 2 ;;
    "aws cloudformation execute-change-set"|"aws cloudformation execute-change-set "*) printf 'lockdown: blocked by deny rule: aws cloudformation execute-change-set\n' >&2; exit 2 ;;
    "aws cloudformation update-stack"|"aws cloudformation update-stack "*) printf 'lockdown: blocked by deny rule: aws cloudformation update-stack\n' >&2; exit 2 ;;
    "aws ec2 authorize-security-group-egress"|"aws ec2 authorize-security-group-egress "*) printf 'lockdown: blocked by deny rule: aws ec2 authorize-security-group-egress\n' >&2; exit 2 ;;
    "aws ec2 authorize-security-group-ingress"|"aws ec2 authorize-security-group-ingress "*) printf 'lockdown: blocked by deny rule: aws ec2 authorize-security-group-ingress\n' >&2; exit 2 ;;
    "aws ec2 create-security-group"|"aws ec2 create-security-group "*) printf 'lockdown: blocked by deny rule: aws ec2 create-security-group\n' >&2; exit 2 ;;
    "aws ec2 delete-security-group"|"aws ec2 delete-security-group "*) printf 'lockdown: blocked by deny rule: aws ec2 delete-security-group\n' >&2; exit 2 ;;
    "aws ec2 modify-instance-attribute"|"aws ec2 modify-instance-attribute "*) printf 'lockdown: blocked by deny rule: aws ec2 modify-instance-attribute\n' >&2; exit 2 ;;
    "aws ec2 reboot-instances"|"aws ec2 reboot-instances "*) printf 'lockdown: blocked by deny rule: aws ec2 reboot-instances\n' >&2; exit 2 ;;
    "aws ec2 revoke-security-group-egress"|"aws ec2 revoke-security-group-egress "*) printf 'lockdown: blocked by deny rule: aws ec2 revoke-security-group-egress\n' >&2; exit 2 ;;
    "aws ec2 revoke-security-group-ingress"|"aws ec2 revoke-security-group-ingress "*) printf 'lockdown: blocked by deny rule: aws ec2 revoke-security-group-ingress\n' >&2; exit 2 ;;
    "aws ec2 run-instances"|"aws ec2 run-instances "*) printf 'lockdown: blocked by deny rule: aws ec2 run-instances\n' >&2; exit 2 ;;
    "aws ec2 start-instances"|"aws ec2 start-instances "*) printf 'lockdown: blocked by deny rule: aws ec2 start-instances\n' >&2; exit 2 ;;
    "aws ec2 stop-instances"|"aws ec2 stop-instances "*) printf 'lockdown: blocked by deny rule: aws ec2 stop-instances\n' >&2; exit 2 ;;
    "aws ec2 terminate-instances"|"aws ec2 terminate-instances "*) printf 'lockdown: blocked by deny rule: aws ec2 terminate-instances\n' >&2; exit 2 ;;
    "aws ecs delete-service"|"aws ecs delete-service "*) printf 'lockdown: blocked by deny rule: aws ecs delete-service\n' >&2; exit 2 ;;
    "aws ecs run-task"|"aws ecs run-task "*) printf 'lockdown: blocked by deny rule: aws ecs run-task\n' >&2; exit 2 ;;
    "aws ecs start-task"|"aws ecs start-task "*) printf 'lockdown: blocked by deny rule: aws ecs start-task\n' >&2; exit 2 ;;
    "aws ecs stop-task"|"aws ecs stop-task "*) printf 'lockdown: blocked by deny rule: aws ecs stop-task\n' >&2; exit 2 ;;
    "aws ecs update-service"|"aws ecs update-service "*) printf 'lockdown: blocked by deny rule: aws ecs update-service\n' >&2; exit 2 ;;
    "aws iam attach-role-policy"|"aws iam attach-role-policy "*) printf 'lockdown: blocked by deny rule: aws iam attach-role-policy\n' >&2; exit 2 ;;
    "aws iam create-access-key"|"aws iam create-access-key "*) printf 'lockdown: blocked by deny rule: aws iam create-access-key\n' >&2; exit 2 ;;
    "aws iam create-policy"|"aws iam create-policy "*) printf 'lockdown: blocked by deny rule: aws iam create-policy\n' >&2; exit 2 ;;
    "aws iam create-role"|"aws iam create-role "*) printf 'lockdown: blocked by deny rule: aws iam create-role\n' >&2; exit 2 ;;
    "aws iam create-user"|"aws iam create-user "*) printf 'lockdown: blocked by deny rule: aws iam create-user\n' >&2; exit 2 ;;
    "aws iam delete-access-key"|"aws iam delete-access-key "*) printf 'lockdown: blocked by deny rule: aws iam delete-access-key\n' >&2; exit 2 ;;
    "aws iam delete-policy"|"aws iam delete-policy "*) printf 'lockdown: blocked by deny rule: aws iam delete-policy\n' >&2; exit 2 ;;
    "aws iam delete-role"|"aws iam delete-role "*) printf 'lockdown: blocked by deny rule: aws iam delete-role\n' >&2; exit 2 ;;
    "aws iam delete-role-policy"|"aws iam delete-role-policy "*) printf 'lockdown: blocked by deny rule: aws iam delete-role-policy\n' >&2; exit 2 ;;
    "aws iam delete-user"|"aws iam delete-user "*) printf 'lockdown: blocked by deny rule: aws iam delete-user\n' >&2; exit 2 ;;
    "aws iam detach-role-policy"|"aws iam detach-role-policy "*) printf 'lockdown: blocked by deny rule: aws iam detach-role-policy\n' >&2; exit 2 ;;
    "aws iam put-role-policy"|"aws iam put-role-policy "*) printf 'lockdown: blocked by deny rule: aws iam put-role-policy\n' >&2; exit 2 ;;
    "aws lambda create-function"|"aws lambda create-function "*) printf 'lockdown: blocked by deny rule: aws lambda create-function\n' >&2; exit 2 ;;
    "aws lambda delete-function"|"aws lambda delete-function "*) printf 'lockdown: blocked by deny rule: aws lambda delete-function\n' >&2; exit 2 ;;
    "aws lambda invoke"|"aws lambda invoke "*) printf 'lockdown: blocked by deny rule: aws lambda invoke\n' >&2; exit 2 ;;
    "aws lambda publish-version"|"aws lambda publish-version "*) printf 'lockdown: blocked by deny rule: aws lambda publish-version\n' >&2; exit 2 ;;
    "aws lambda update-function-code"|"aws lambda update-function-code "*) printf 'lockdown: blocked by deny rule: aws lambda update-function-code\n' >&2; exit 2 ;;
    "aws lambda update-function-configuration"|"aws lambda update-function-configuration "*) printf 'lockdown: blocked by deny rule: aws lambda update-function-configuration\n' >&2; exit 2 ;;
    "aws route53 change-resource-record-sets"|"aws route53 change-resource-record-sets "*) printf 'lockdown: blocked by deny rule: aws route53 change-resource-record-sets\n' >&2; exit 2 ;;
    "aws route53 create-hosted-zone"|"aws route53 create-hosted-zone "*) printf 'lockdown: blocked by deny rule: aws route53 create-hosted-zone\n' >&2; exit 2 ;;
    "aws route53 delete-hosted-zone"|"aws route53 delete-hosted-zone "*) printf 'lockdown: blocked by deny rule: aws route53 delete-hosted-zone\n' >&2; exit 2 ;;
    "aws s3 cp"|"aws s3 cp "*) printf 'lockdown: blocked by deny rule: aws s3 cp\n' >&2; exit 2 ;;
    "aws s3 mb"|"aws s3 mb "*) printf 'lockdown: blocked by deny rule: aws s3 mb\n' >&2; exit 2 ;;
    "aws s3 mv"|"aws s3 mv "*) printf 'lockdown: blocked by deny rule: aws s3 mv\n' >&2; exit 2 ;;
    "aws s3 rb"|"aws s3 rb "*) printf 'lockdown: blocked by deny rule: aws s3 rb\n' >&2; exit 2 ;;
    "aws s3 rm"|"aws s3 rm "*) printf 'lockdown: blocked by deny rule: aws s3 rm\n' >&2; exit 2 ;;
    "aws s3 sync"|"aws s3 sync "*) printf 'lockdown: blocked by deny rule: aws s3 sync\n' >&2; exit 2 ;;
    "aws s3api copy-object"|"aws s3api copy-object "*) printf 'lockdown: blocked by deny rule: aws s3api copy-object\n' >&2; exit 2 ;;
    "aws s3api create-bucket"|"aws s3api create-bucket "*) printf 'lockdown: blocked by deny rule: aws s3api create-bucket\n' >&2; exit 2 ;;
    "aws s3api delete-bucket"|"aws s3api delete-bucket "*) printf 'lockdown: blocked by deny rule: aws s3api delete-bucket\n' >&2; exit 2 ;;
    "aws s3api delete-object"|"aws s3api delete-object "*) printf 'lockdown: blocked by deny rule: aws s3api delete-object\n' >&2; exit 2 ;;
    "aws s3api delete-objects"|"aws s3api delete-objects "*) printf 'lockdown: blocked by deny rule: aws s3api delete-objects\n' >&2; exit 2 ;;
    "aws s3api put-bucket-policy"|"aws s3api put-bucket-policy "*) printf 'lockdown: blocked by deny rule: aws s3api put-bucket-policy\n' >&2; exit 2 ;;
    "aws s3api put-object"|"aws s3api put-object "*) printf 'lockdown: blocked by deny rule: aws s3api put-object\n' >&2; exit 2 ;;
    "aws ssm delete-parameter"|"aws ssm delete-parameter "*) printf 'lockdown: blocked by deny rule: aws ssm delete-parameter\n' >&2; exit 2 ;;
    "aws ssm delete-parameters"|"aws ssm delete-parameters "*) printf 'lockdown: blocked by deny rule: aws ssm delete-parameters\n' >&2; exit 2 ;;
    "aws ssm get-parameter"|"aws ssm get-parameter "*) printf 'lockdown: blocked by deny rule: aws ssm get-parameter\n' >&2; exit 2 ;;
    "aws ssm get-parameters"|"aws ssm get-parameters "*) printf 'lockdown: blocked by deny rule: aws ssm get-parameters\n' >&2; exit 2 ;;
    "aws ssm get-parameters-by-path"|"aws ssm get-parameters-by-path "*) printf 'lockdown: blocked by deny rule: aws ssm get-parameters-by-path\n' >&2; exit 2 ;;
    "aws ssm put-parameter"|"aws ssm put-parameter "*) printf 'lockdown: blocked by deny rule: aws ssm put-parameter\n' >&2; exit 2 ;;
    "aws ssm send-command"|"aws ssm send-command "*) printf 'lockdown: blocked by deny rule: aws ssm send-command\n' >&2; exit 2 ;;
    "aws ssm start-session"|"aws ssm start-session "*) printf 'lockdown: blocked by deny rule: aws ssm start-session\n' >&2; exit 2 ;;
    "bash"|"bash "*) printf 'lockdown: blocked by deny rule: bash\n' >&2; exit 2 ;;
    "brew"|"brew "*) printf 'lockdown: blocked by deny rule: brew\n' >&2; exit 2 ;;
    "bun"|"bun "*) printf 'lockdown: blocked by deny rule: bun\n' >&2; exit 2 ;;
    "bundle"|"bundle "*) printf 'lockdown: blocked by deny rule: bundle\n' >&2; exit 2 ;;
    "cargo"|"cargo "*) printf 'lockdown: blocked by deny rule: cargo\n' >&2; exit 2 ;;
    "cmd"|"cmd "*) printf 'lockdown: blocked by deny rule: cmd\n' >&2; exit 2 ;;
    "cmd.exe"|"cmd.exe "*) printf 'lockdown: blocked by deny rule: cmd.exe\n' >&2; exit 2 ;;
    "cscript"|"cscript "*) printf 'lockdown: blocked by deny rule: cscript\n' >&2; exit 2 ;;
    "cscript.exe"|"cscript.exe "*) printf 'lockdown: blocked by deny rule: cscript.exe\n' >&2; exit 2 ;;
    "dash"|"dash "*) printf 'lockdown: blocked by deny rule: dash\n' >&2; exit 2 ;;
    "deno"|"deno "*) printf 'lockdown: blocked by deny rule: deno\n' >&2; exit 2 ;;
    "docker"|"docker "*) printf 'lockdown: blocked by deny rule: docker\n' >&2; exit 2 ;;
    "env"|"env "*) printf 'lockdown: blocked by deny rule: env\n' >&2; exit 2 ;;
    "exec"|"exec "*) printf 'lockdown: blocked by deny rule: exec\n' >&2; exit 2 ;;
    "fish"|"fish "*) printf 'lockdown: blocked by deny rule: fish\n' >&2; exit 2 ;;
    "gcloud"|"gcloud "*) printf 'lockdown: blocked by deny rule: gcloud\n' >&2; exit 2 ;;
    "gem"|"gem "*) printf 'lockdown: blocked by deny rule: gem\n' >&2; exit 2 ;;
    "gh api"|"gh api "*) printf 'lockdown: blocked by deny rule: gh api\n' >&2; exit 2 ;;
    "gh auth login"|"gh auth login "*) printf 'lockdown: blocked by deny rule: gh auth login\n' >&2; exit 2 ;;
    "gh auth logout"|"gh auth logout "*) printf 'lockdown: blocked by deny rule: gh auth logout\n' >&2; exit 2 ;;
    "gh auth refresh"|"gh auth refresh "*) printf 'lockdown: blocked by deny rule: gh auth refresh\n' >&2; exit 2 ;;
    "gh auth setup-git"|"gh auth setup-git "*) printf 'lockdown: blocked by deny rule: gh auth setup-git\n' >&2; exit 2 ;;
    "gh cache delete"|"gh cache delete "*) printf 'lockdown: blocked by deny rule: gh cache delete\n' >&2; exit 2 ;;
    "gh issue close"|"gh issue close "*) printf 'lockdown: blocked by deny rule: gh issue close\n' >&2; exit 2 ;;
    "gh issue comment"|"gh issue comment "*) printf 'lockdown: blocked by deny rule: gh issue comment\n' >&2; exit 2 ;;
    "gh issue create"|"gh issue create "*) printf 'lockdown: blocked by deny rule: gh issue create\n' >&2; exit 2 ;;
    "gh issue delete"|"gh issue delete "*) printf 'lockdown: blocked by deny rule: gh issue delete\n' >&2; exit 2 ;;
    "gh issue edit"|"gh issue edit "*) printf 'lockdown: blocked by deny rule: gh issue edit\n' >&2; exit 2 ;;
    "gh issue lock"|"gh issue lock "*) printf 'lockdown: blocked by deny rule: gh issue lock\n' >&2; exit 2 ;;
    "gh issue pin"|"gh issue pin "*) printf 'lockdown: blocked by deny rule: gh issue pin\n' >&2; exit 2 ;;
    "gh issue reopen"|"gh issue reopen "*) printf 'lockdown: blocked by deny rule: gh issue reopen\n' >&2; exit 2 ;;
    "gh issue transfer"|"gh issue transfer "*) printf 'lockdown: blocked by deny rule: gh issue transfer\n' >&2; exit 2 ;;
    "gh issue unlock"|"gh issue unlock "*) printf 'lockdown: blocked by deny rule: gh issue unlock\n' >&2; exit 2 ;;
    "gh issue unpin"|"gh issue unpin "*) printf 'lockdown: blocked by deny rule: gh issue unpin\n' >&2; exit 2 ;;
    "gh label clone"|"gh label clone "*) printf 'lockdown: blocked by deny rule: gh label clone\n' >&2; exit 2 ;;
    "gh label create"|"gh label create "*) printf 'lockdown: blocked by deny rule: gh label create\n' >&2; exit 2 ;;
    "gh label delete"|"gh label delete "*) printf 'lockdown: blocked by deny rule: gh label delete\n' >&2; exit 2 ;;
    "gh label edit"|"gh label edit "*) printf 'lockdown: blocked by deny rule: gh label edit\n' >&2; exit 2 ;;
    "gh pr close"|"gh pr close "*) printf 'lockdown: blocked by deny rule: gh pr close\n' >&2; exit 2 ;;
    "gh pr comment"|"gh pr comment "*) printf 'lockdown: blocked by deny rule: gh pr comment\n' >&2; exit 2 ;;
    "gh pr create"|"gh pr create "*) printf 'lockdown: blocked by deny rule: gh pr create\n' >&2; exit 2 ;;
    "gh pr edit"|"gh pr edit "*) printf 'lockdown: blocked by deny rule: gh pr edit\n' >&2; exit 2 ;;
    "gh pr lock"|"gh pr lock "*) printf 'lockdown: blocked by deny rule: gh pr lock\n' >&2; exit 2 ;;
    "gh pr merge"|"gh pr merge "*) printf 'lockdown: blocked by deny rule: gh pr merge\n' >&2; exit 2 ;;
    "gh pr ready"|"gh pr ready "*) printf 'lockdown: blocked by deny rule: gh pr ready\n' >&2; exit 2 ;;
    "gh pr reopen"|"gh pr reopen "*) printf 'lockdown: blocked by deny rule: gh pr reopen\n' >&2; exit 2 ;;
    "gh pr review"|"gh pr review "*) printf 'lockdown: blocked by deny rule: gh pr review\n' >&2; exit 2 ;;
    "gh pr unlock"|"gh pr unlock "*) printf 'lockdown: blocked by deny rule: gh pr unlock\n' >&2; exit 2 ;;
    "gh pr update-branch"|"gh pr update-branch "*) printf 'lockdown: blocked by deny rule: gh pr update-branch\n' >&2; exit 2 ;;
    "gh release create"|"gh release create "*) printf 'lockdown: blocked by deny rule: gh release create\n' >&2; exit 2 ;;
    "gh release delete"|"gh release delete "*) printf 'lockdown: blocked by deny rule: gh release delete\n' >&2; exit 2 ;;
    "gh release download"|"gh release download "*) printf 'lockdown: blocked by deny rule: gh release download\n' >&2; exit 2 ;;
    "gh release edit"|"gh release edit "*) printf 'lockdown: blocked by deny rule: gh release edit\n' >&2; exit 2 ;;
    "gh release upload"|"gh release upload "*) printf 'lockdown: blocked by deny rule: gh release upload\n' >&2; exit 2 ;;
    "gh repo archive"|"gh repo archive "*) printf 'lockdown: blocked by deny rule: gh repo archive\n' >&2; exit 2 ;;
    "gh repo create"|"gh repo create "*) printf 'lockdown: blocked by deny rule: gh repo create\n' >&2; exit 2 ;;
    "gh repo delete"|"gh repo delete "*) printf 'lockdown: blocked by deny rule: gh repo delete\n' >&2; exit 2 ;;
    "gh repo deploy-key"|"gh repo deploy-key "*) printf 'lockdown: blocked by deny rule: gh repo deploy-key\n' >&2; exit 2 ;;
    "gh repo edit"|"gh repo edit "*) printf 'lockdown: blocked by deny rule: gh repo edit\n' >&2; exit 2 ;;
    "gh repo fork"|"gh repo fork "*) printf 'lockdown: blocked by deny rule: gh repo fork\n' >&2; exit 2 ;;
    "gh repo rename"|"gh repo rename "*) printf 'lockdown: blocked by deny rule: gh repo rename\n' >&2; exit 2 ;;
    "gh repo unarchive"|"gh repo unarchive "*) printf 'lockdown: blocked by deny rule: gh repo unarchive\n' >&2; exit 2 ;;
    "gh ruleset create"|"gh ruleset create "*) printf 'lockdown: blocked by deny rule: gh ruleset create\n' >&2; exit 2 ;;
    "gh ruleset delete"|"gh ruleset delete "*) printf 'lockdown: blocked by deny rule: gh ruleset delete\n' >&2; exit 2 ;;
    "gh ruleset edit"|"gh ruleset edit "*) printf 'lockdown: blocked by deny rule: gh ruleset edit\n' >&2; exit 2 ;;
    "gh run cancel"|"gh run cancel "*) printf 'lockdown: blocked by deny rule: gh run cancel\n' >&2; exit 2 ;;
    "gh run delete"|"gh run delete "*) printf 'lockdown: blocked by deny rule: gh run delete\n' >&2; exit 2 ;;
    "gh run rerun"|"gh run rerun "*) printf 'lockdown: blocked by deny rule: gh run rerun\n' >&2; exit 2 ;;
    "gh secret delete"|"gh secret delete "*) printf 'lockdown: blocked by deny rule: gh secret delete\n' >&2; exit 2 ;;
    "gh secret set"|"gh secret set "*) printf 'lockdown: blocked by deny rule: gh secret set\n' >&2; exit 2 ;;
    "gh variable delete"|"gh variable delete "*) printf 'lockdown: blocked by deny rule: gh variable delete\n' >&2; exit 2 ;;
    "gh variable set"|"gh variable set "*) printf 'lockdown: blocked by deny rule: gh variable set\n' >&2; exit 2 ;;
    "gh workflow disable"|"gh workflow disable "*) printf 'lockdown: blocked by deny rule: gh workflow disable\n' >&2; exit 2 ;;
    "gh workflow enable"|"gh workflow enable "*) printf 'lockdown: blocked by deny rule: gh workflow enable\n' >&2; exit 2 ;;
    "gh workflow run"|"gh workflow run "*) printf 'lockdown: blocked by deny rule: gh workflow run\n' >&2; exit 2 ;;
    "git clean -fd"|"git clean -fd "*) printf 'lockdown: blocked by deny rule: git clean -fd\n' >&2; exit 2 ;;
    "git push --force"|"git push --force "*) printf 'lockdown: blocked by deny rule: git push --force\n' >&2; exit 2 ;;
    "git push -f"|"git push -f "*) printf 'lockdown: blocked by deny rule: git push -f\n' >&2; exit 2 ;;
    "git reset --hard"|"git reset --hard "*) printf 'lockdown: blocked by deny rule: git reset --hard\n' >&2; exit 2 ;;
    "go run"|"go run "*) printf 'lockdown: blocked by deny rule: go run\n' >&2; exit 2 ;;
    "helm"|"helm "*) printf 'lockdown: blocked by deny rule: helm\n' >&2; exit 2 ;;
    "invoke"|"invoke "*) printf 'lockdown: blocked by deny rule: invoke\n' >&2; exit 2 ;;
    "just"|"just "*) printf 'lockdown: blocked by deny rule: just\n' >&2; exit 2 ;;
    "ksh"|"ksh "*) printf 'lockdown: blocked by deny rule: ksh\n' >&2; exit 2 ;;
    "kubectl annotate"|"kubectl annotate "*) printf 'lockdown: blocked by deny rule: kubectl annotate\n' >&2; exit 2 ;;
    "kubectl apply"|"kubectl apply "*) printf 'lockdown: blocked by deny rule: kubectl apply\n' >&2; exit 2 ;;
    "kubectl attach"|"kubectl attach "*) printf 'lockdown: blocked by deny rule: kubectl attach\n' >&2; exit 2 ;;
    "kubectl autoscale"|"kubectl autoscale "*) printf 'lockdown: blocked by deny rule: kubectl autoscale\n' >&2; exit 2 ;;
    "kubectl cordon"|"kubectl cordon "*) printf 'lockdown: blocked by deny rule: kubectl cordon\n' >&2; exit 2 ;;
    "kubectl cp"|"kubectl cp "*) printf 'lockdown: blocked by deny rule: kubectl cp\n' >&2; exit 2 ;;
    "kubectl create"|"kubectl create "*) printf 'lockdown: blocked by deny rule: kubectl create\n' >&2; exit 2 ;;
    "kubectl debug"|"kubectl debug "*) printf 'lockdown: blocked by deny rule: kubectl debug\n' >&2; exit 2 ;;
    "kubectl delete"|"kubectl delete "*) printf 'lockdown: blocked by deny rule: kubectl delete\n' >&2; exit 2 ;;
    "kubectl drain"|"kubectl drain "*) printf 'lockdown: blocked by deny rule: kubectl drain\n' >&2; exit 2 ;;
    "kubectl edit"|"kubectl edit "*) printf 'lockdown: blocked by deny rule: kubectl edit\n' >&2; exit 2 ;;
    "kubectl exec"|"kubectl exec "*) printf 'lockdown: blocked by deny rule: kubectl exec\n' >&2; exit 2 ;;
    "kubectl expose"|"kubectl expose "*) printf 'lockdown: blocked by deny rule: kubectl expose\n' >&2; exit 2 ;;
    "kubectl kustomize"|"kubectl kustomize "*) printf 'lockdown: blocked by deny rule: kubectl kustomize\n' >&2; exit 2 ;;
    "kubectl label"|"kubectl label "*) printf 'lockdown: blocked by deny rule: kubectl label\n' >&2; exit 2 ;;
    "kubectl patch"|"kubectl patch "*) printf 'lockdown: blocked by deny rule: kubectl patch\n' >&2; exit 2 ;;
    "kubectl port-forward"|"kubectl port-forward "*) printf 'lockdown: blocked by deny rule: kubectl port-forward\n' >&2; exit 2 ;;
    "kubectl proxy"|"kubectl proxy "*) printf 'lockdown: blocked by deny rule: kubectl proxy\n' >&2; exit 2 ;;
    "kubectl replace"|"kubectl replace "*) printf 'lockdown: blocked by deny rule: kubectl replace\n' >&2; exit 2 ;;
    "kubectl rollout pause"|"kubectl rollout pause "*) printf 'lockdown: blocked by deny rule: kubectl rollout pause\n' >&2; exit 2 ;;
    "kubectl rollout restart"|"kubectl rollout restart "*) printf 'lockdown: blocked by deny rule: kubectl rollout restart\n' >&2; exit 2 ;;
    "kubectl rollout resume"|"kubectl rollout resume "*) printf 'lockdown: blocked by deny rule: kubectl rollout resume\n' >&2; exit 2 ;;
    "kubectl rollout undo"|"kubectl rollout undo "*) printf 'lockdown: blocked by deny rule: kubectl rollout undo\n' >&2; exit 2 ;;
    "kubectl run"|"kubectl run "*) printf 'lockdown: blocked by deny rule: kubectl run\n' >&2; exit 2 ;;
    "kubectl scale"|"kubectl scale "*) printf 'lockdown: blocked by deny rule: kubectl scale\n' >&2; exit 2 ;;
    "kubectl set"|"kubectl set "*) printf 'lockdown: blocked by deny rule: kubectl set\n' >&2; exit 2 ;;
    "kubectl taint"|"kubectl taint "*) printf 'lockdown: blocked by deny rule: kubectl taint\n' >&2; exit 2 ;;
    "kubectl uncordon"|"kubectl uncordon "*) printf 'lockdown: blocked by deny rule: kubectl uncordon\n' >&2; exit 2 ;;
    "make"|"make "*) printf 'lockdown: blocked by deny rule: make\n' >&2; exit 2 ;;
    "mshta"|"mshta "*) printf 'lockdown: blocked by deny rule: mshta\n' >&2; exit 2 ;;
    "mshta.exe"|"mshta.exe "*) printf 'lockdown: blocked by deny rule: mshta.exe\n' >&2; exit 2 ;;
    "node"|"node "*) printf 'lockdown: blocked by deny rule: node\n' >&2; exit 2 ;;
    "nox"|"nox "*) printf 'lockdown: blocked by deny rule: nox\n' >&2; exit 2 ;;
    "npm"|"npm "*) printf 'lockdown: blocked by deny rule: npm\n' >&2; exit 2 ;;
    "osascript"|"osascript "*) printf 'lockdown: blocked by deny rule: osascript\n' >&2; exit 2 ;;
    "perl"|"perl "*) printf 'lockdown: blocked by deny rule: perl\n' >&2; exit 2 ;;
    "pip"|"pip "*) printf 'lockdown: blocked by deny rule: pip\n' >&2; exit 2 ;;
    "pipx"|"pipx "*) printf 'lockdown: blocked by deny rule: pipx\n' >&2; exit 2 ;;
    "pnpm"|"pnpm "*) printf 'lockdown: blocked by deny rule: pnpm\n' >&2; exit 2 ;;
    "poetry"|"poetry "*) printf 'lockdown: blocked by deny rule: poetry\n' >&2; exit 2 ;;
    "powershell"|"powershell "*) printf 'lockdown: blocked by deny rule: powershell\n' >&2; exit 2 ;;
    "powershell.exe"|"powershell.exe "*) printf 'lockdown: blocked by deny rule: powershell.exe\n' >&2; exit 2 ;;
    "pwsh"|"pwsh "*) printf 'lockdown: blocked by deny rule: pwsh\n' >&2; exit 2 ;;
    "pwsh.exe"|"pwsh.exe "*) printf 'lockdown: blocked by deny rule: pwsh.exe\n' >&2; exit 2 ;;
    "python"|"python "*) printf 'lockdown: blocked by deny rule: python\n' >&2; exit 2 ;;
    "python3"|"python3 "*) printf 'lockdown: blocked by deny rule: python3\n' >&2; exit 2 ;;
    "regsvr32"|"regsvr32 "*) printf 'lockdown: blocked by deny rule: regsvr32\n' >&2; exit 2 ;;
    "regsvr32.exe"|"regsvr32.exe "*) printf 'lockdown: blocked by deny rule: regsvr32.exe\n' >&2; exit 2 ;;
    "rsync"|"rsync "*) printf 'lockdown: blocked by deny rule: rsync\n' >&2; exit 2 ;;
    "ruby"|"ruby "*) printf 'lockdown: blocked by deny rule: ruby\n' >&2; exit 2 ;;
    "rundll32"|"rundll32 "*) printf 'lockdown: blocked by deny rule: rundll32\n' >&2; exit 2 ;;
    "rundll32.exe"|"rundll32.exe "*) printf 'lockdown: blocked by deny rule: rundll32.exe\n' >&2; exit 2 ;;
    "scp"|"scp "*) printf 'lockdown: blocked by deny rule: scp\n' >&2; exit 2 ;;
    "sh"|"sh "*) printf 'lockdown: blocked by deny rule: sh\n' >&2; exit 2 ;;
    "ssh"|"ssh "*) printf 'lockdown: blocked by deny rule: ssh\n' >&2; exit 2 ;;
    "sshfs"|"sshfs "*) printf 'lockdown: blocked by deny rule: sshfs\n' >&2; exit 2 ;;
    "tailscale"|"tailscale "*) printf 'lockdown: blocked by deny rule: tailscale\n' >&2; exit 2 ;;
    "task"|"task "*) printf 'lockdown: blocked by deny rule: task\n' >&2; exit 2 ;;
    "terraform"|"terraform "*) printf 'lockdown: blocked by deny rule: terraform\n' >&2; exit 2 ;;
    "tflint"|"tflint "*) printf 'lockdown: blocked by deny rule: tflint\n' >&2; exit 2 ;;
    "tfsec"|"tfsec "*) printf 'lockdown: blocked by deny rule: tfsec\n' >&2; exit 2 ;;
    "tox"|"tox "*) printf 'lockdown: blocked by deny rule: tox\n' >&2; exit 2 ;;
    "uv"|"uv "*) printf 'lockdown: blocked by deny rule: uv\n' >&2; exit 2 ;;
    "wscript"|"wscript "*) printf 'lockdown: blocked by deny rule: wscript\n' >&2; exit 2 ;;
    "wscript.exe"|"wscript.exe "*) printf 'lockdown: blocked by deny rule: wscript.exe\n' >&2; exit 2 ;;
    "xargs"|"xargs "*) printf 'lockdown: blocked by deny rule: xargs\n' >&2; exit 2 ;;
    "yarn"|"yarn "*) printf 'lockdown: blocked by deny rule: yarn\n' >&2; exit 2 ;;
    "zsh"|"zsh "*) printf 'lockdown: blocked by deny rule: zsh\n' >&2; exit 2 ;;
  esac
}

# Iterate segments. heredoc is a single-process loop so an exit inside
# check_segment terminates the whole script.
while IFS= read -r seg; do
  check_segment "$seg"
done <<EOF
$SEGMENTS
EOF

exit 0
