#!/bin/sh
# Auto-generated by coily. Do not edit; regenerate via coily lockdown --apply --replace.
#
# Delegates to coily hook pre-tool-use, which calls the shared
# cli-guard/hook engine with coily's integrity rules + route
# table. See coilysiren/coily#248 + cli-guard#74.
exec coily hook pre-tool-use
