import { createRequire } from "node:module"
import { umbraDocs, umbraDocsFlat } from "../data/umbra-docs.js"

// The stamp is generated by scripts/sync-project-docs.py, so it is read here
// rather than restated in the manifest. See docs/project-docs-mount.md.
const mountSource = createRequire(import.meta.url)(
  "../data/docs-mount-source.json"
)

export default {
  shelves: umbraDocs,
  flat: umbraDocsFlat,
  source: mountSource.umbra,
}
