name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    container: node:24.18.0
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test:quick
  test-e2e:
    runs-on: ubuntu-24.04
    container: cypress/included:15.19.0
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test:e2e:ci
